name: 🚨 Signaler un bug
description: Signalez un problème ou un dysfonctionnement
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Avant de créer un bug, merci de :**
        - Vérifier si le bug a déjà été signalé : [bugs en cours ou déjà traités](https://github.com/ansforge/finess/issues?q=is%3Aissue+label%3Abug)
        - Fournir des informations claires pour faciliter le traitement.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré
    validations:
      required: true
